# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('country_host', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ReportingPeriod'),
            preserve_default=False,
        ),
    ]
