# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicproducts',
            old_name='indexDate',
            new_name='index_date',
        ),
        migrations.RenameField(
            model_name='historicproducts',
            old_name='indexRate',
            new_name='index_rate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='historicRef',
            new_name='historic_ref',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='reportingPercentage',
            new_name='reporting_percentage',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='reportingPeriod',
            new_name='reporting_period',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='billingAddress',
            new_name='billing_address',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='expirationCardDate',
            new_name='expiration_card_date',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='securityCode',
            new_name='security_code',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='validPayment',
            new_name='valid_payment',
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
