# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170806_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marketplace',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Marketplace'),
            preserve_default=False,
        ),
    ]
