# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170718_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingperiod',
            name='day_of_week',
            field=models.CharField(default='-1', max_length=10),
            preserve_default=False,
        ),
    ]
