# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reportingperiod_day_of_week'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportingperiod',
            table='main_reporting_period',
        ),
    ]
