# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170718_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reporting_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='value',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
