# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 18:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170821_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phrases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), null=True, size=None),
        ),
    ]
