# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170826_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='billing_address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
