# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='historic_ref',
        ),
        migrations.AddField(
            model_name='keywords',
            name='index_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HistoricProducts',
        ),
    ]
