# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170719_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='index_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
