# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='billing_address',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
