# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-05 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170829_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='indexing',
            field=models.CharField(max_length=20),
        ),
    ]
