# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_product_crawl_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_confirmed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
