# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-05 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170905_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='indexing',
            field=models.CharField(max_length=30),
        ),
    ]
