# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-24 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170905_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='disabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=500),
        ),
    ]
