# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profile_account_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHistoricIndexing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexing_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('indexed_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
        ),
    ]
