# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-29 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170927_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='valid_payment',
            new_name='valid_subscription',
        ),
    ]
